
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-4pm-2
owner: ucsb-cs156-w24
repo_name: team01-w24-4pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxNjM1Njk1","is_bot":false,"login":"rkirsur","name":"Ritu Kirsur"},"headRefName":"Ritu-Tides-Controller","number":32,"title":"Ritu tides controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-2/pull/32"},{"author":{"id":"U_kgDOBXgO1Q","is_bot":false,"login":"rohankumar2025","name":""},"headRefName":"Rohan-ZipCode-Controller","number":31,"title":"Rohan zip code controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-2/pull/31"},{"author":{"id":"MDQ6VXNlcjMzMjg5NDM1","is_bot":false,"login":"BK1031","name":"Bharat Kathi"},"headRefName":"revert-26-Kyle-University","number":29,"title":"Revert \"University Service and Tests\"","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-2/pull/29"},{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-PublicHoliday-Controller","number":25,"title":"AS - Add PublicHoliday Service and Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-2/pull/25"},{"author":{"id":"MDQ6VXNlcjYxNjM1Njk1","is_bot":false,"login":"rkirsur","name":"Ritu Kirsur"},"headRefName":"Ritu-Tides","number":24,"title":"Ritu tides service and test","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-2/pull/24"},{"author":{"id":"MDQ6VXNlcjMzMjg5NDM1","is_bot":false,"login":"BK1031","name":"Bharat Kathi"},"headRefName":"Bharat-HomeController","number":23,"title":"Update HomeController","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-2/pull/23"},{"author":{"id":"U_kgDOBXgO1Q","is_bot":false,"login":"rohankumar2025","name":""},"headRefName":"Rohan-ZipCodeQueryService","number":22,"title":"Rohan zip code query service","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-2/pull/22"},{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-PublicHoliday","number":21,"title":"Added public holiday service and tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-2/pull/21"}]
